=== akamai/cli-request-control/assets/rule_schema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema#",
  "title" : "IP/GEO MATCH RULE",
  "description" : "applied to create/update match rule requests for IG cloudlets, where requests are of the form: POST|PUT /api/v2/policies/{policyId}/versions/{versionId}/rules/{ruleId}",
  "version" : "1.0",
  "type" : "object",
  "definitions" : {
    "matchRuleType" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : [ "string", "null" ],
          "maxLength" : 8192
        },
        "type" : {
          "type" : "string",
          "enum" : [ "igMatchRule" ]
        },
        "start" : {
          "type" : "integer",
          "minimum" : 0
        },
        "end" : {
          "type" : "integer",
          "minimum" : 0
        },
        "id" : {
          "type" : [ "integer", "null" ]
        },
        "matches" : {
          "type" : [ "array", "null" ],
          "items" : {
            "$ref" : "#/definitions/matchCriteriaType"
          }
        },
        "disabled" : {
          "type" : "boolean"
        },
        "akaRuleId" : {
          "type" : "string"
        },
        "allowDeny" : {
          "type" : "string",
          "enum" : [ "allow", "deny", "denybranded" ]
        },
        "matchesAlways" : {
          "type" : "boolean"
        }
      },
      "additionalProperties" : false,
      "required" : [ "type", "allowDeny" ],
      "not" : {
        "required" : [ "matches", "matchesAlways" ]
      }
    },
    "matchCriteriaType" : {
      "type" : "object",
      "properties" : {
        "caseSensitive" : {
          "type" : "boolean"
        },
        "matchValue" : {
          "type" : "string",
          "minLength" : 1,
          "maxLength" : 8192
        },
        "negate" : {
          "type" : "boolean"
        },
        "matchOperator" : {
          "type" : "string",
          "enum" : [ "contains", "exists", "equals" ]
        },
        "matchType" : {
          "type" : "string",
          "enum" : [ "clientip", "continent", "cookie", "countrycode", "deviceCharacteristics", "extension", "header", "hostname", "method", "path", "protocol", "proxy", "query", "regioncode" ]
        },
        "checkIPs" : {
          "type" : "string",
          "enum" : [ null, "CONNECTING_IP", "XFF_HEADERS", "CONNECTING_IP XFF_HEADERS" ]
        },
        "objectMatchValue" : {
          "$ref" : "#/definitions/objectMatchValueType"
        }
      },
      "oneOf" : [ {
        "required" : [ "matchType", "matchValue" ]
      }, {
        "required" : [ "matchType", "objectMatchValue" ]
      } ],
      "additionalProperties" : false
    },
    "objectMatchValueRangeOrSimpleSubtype" : {
      "type" : "object",
      "properties" : {
        "type" : {
          "type" : "string",
          "enum" : [ "range", "simple" ]
        },
        "value" : {
          "type" : [ "array", "null" ]
        }
      },
      "required" : [ "type", "value" ],
      "additionalProperties" : false
    },
    "objectMatchValueObjectSubtype" : {
      "type" : "object",
      "properties" : {
        "name" : {
          "type" : "string",
          "minLength" : 1,
          "maxLength" : 8192
        },
        "type" : {
          "type" : "string",
          "enum" : [ "object" ]
        },
        "nameCaseSensitive" : {
          "type" : "boolean"
        },
        "nameHasWildcard" : {
          "type" : "boolean"
        },
        "options" : {
          "type" : "object",
          "properties" : {
            "value" : {
              "type" : [ "array", "null" ]
            },
            "valueHasWildcard" : {
              "type" : "boolean"
            },
            "valueCaseSensitive" : {
              "type" : "boolean"
            },
            "valueEscaped" : {
              "type" : "boolean"
            }
          },
          "additionalProperties" : false
        }
      },
      "required" : [ "name", "type" ],
      "additionalProperties" : false
    },
    "objectMatchValueType" : {
      "type" : "object",
      "oneOf" : [ {
        "$ref" : "#/definitions/objectMatchValueRangeOrSimpleSubtype"
      }, {
        "$ref" : "#/definitions/objectMatchValueObjectSubtype"
      } ]
    }
  },
  "location" : "/api/v2/schemas/match_rule-IG-1.0.json",
  "$ref" : "#/definitions/matchRuleType"
}

=== akamai/cli-request-control/assets/test_rule.json
{
        "allowDeny": "deny",
        "start": 0, 
        "end": 0, 
        "id": 0, 
        "matches": [
            {
                "caseSensitive": false, 
                "matchOperator": "equals",
                "matchType": "extension", 
                "matchValue": "jpg", 
                "negate": true
            }
        ], 
        "name": "Rule modified by API!", 
        "type": "igMatchRule"
    }

=== akamai/cli-request-control/assets/rule_template.json
{
    "name": "",
    "allowDeny": "allow",
    "start": 0,
    "end": 0, 
    "id": 0, 
    "matches": [
        {
            "matchValue": "1.2.3.4 5.6.7.8", 
            "checkIPs": "CONNECTING_IP XFF_HEADERS", 
            "caseSensitive": false, 
            "negate": false, 
            "matchType": "clientip", 
            "matchOperator": "equals"
        }
    ], 
    "type": "igMatchRule"
}
